### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vordme** [jeroenbeijer/SDRReceiver#13]
Hi everyone
Thanks for the software,
When starting SDRReceiver, I received an error message "sample_rate ini file key not found or equal to zero, check ini file name and key values"
download the .ini file again and the same error

thanks 
Claudio

**Comment by jeroenbeijer** [comment]
Hi Claudio,

In this case it would seem the program finds the ini file (otherwise you would have gotten a different error) but it seems the value for sample_rate is not found or it is zero. Can you make sure the ini file you pass with the -s switch starts with a valid value for sample_rate, i.e. 

sample_rate=1536000

/Jeroen

**Comment by jeroenbeijer** [comment]
Closing.
